### ISSUE TITLE
hot to call logout?

### ISSUE THREAD

**Issue by cmnstmntmn** [akagadovskiy/ng-admin-jwt-auth#1]
is there a fancy way to logout this way, by calling the responssible controller?

`
<li><a href="#" ng-click="logoutController()"> Logout</a></li>
`

instead of 

`
<a href="/#logout">Logout</a>
`

**Comment by akagadovskiy** [comment]
Hi @cmnstmntmn . You could use the first method if you have an access to logoutController in current scope.
You can find example of logout configuration in demo app <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth-demoapp/blob/master/public/app.js#L278">here</a>
