### ISSUE TITLE
Role system

### ISSUE THREAD

**Issue by miguelslemos** [akagadovskiy/ng-admin-jwt-auth#11]
Hi,
when role system will be available?

Thanks, good job guys

**Comment by akagadovskiy** [comment]
Hello, 
you can create a different configurations for ng-admin for different users and it will be the same as roles system

**Comment by miguelslemos** [comment]
Sorry, can you explain a little bit ? Please. How i can create different configurations based in user role?

**Comment by akagadovskiy** [comment]
@miguelslemos  Yes. Here is the link to the related topic.

[https://github.com/marmelab/ng-admin-demo/pull/8](url)
