### ISSUE TITLE
how to force login redirect, when token expired?

### ISSUE THREAD

**Issue by cmnstmntmn** [akagadovskiy/ng-admin-jwt-auth#2]

**Comment by akagadovskiy** [comment]
Hi. Module automatically checks is token expired or not and redirects to login page if it's expired.

**Comment by cmnstmntmn** [comment]
does the check is done when i click something, 
or automatically after a period of time?

**Comment by akagadovskiy** [comment]
It checks when you click on something. For more information you can see <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth/blob/master/js/module.js#L39">this</a>

**Comment by cmnstmntmn** [comment]
ty ;)

**Comment by akagadovskiy** [comment]
welcome)
